### ISSUE TITLE
Coastal Comm-Haz Resliency form in Reporting Call

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Bug-Tracker#105]
The "Country" field should be "County"

"Number of Resilency training" is ambiguous and needs to be reworded to "Number of resiliency trainings provided"

For clarification, can we change "Was community hazard resiliency improved" to "Was community hazard resiliency improved? (Y/N)"

(https://cloud.githubusercontent.com/assets/17415806/13749311/2b65fe9a-e9d7-11e5-9dcd-8c606b9e3eac.png)

**Comment by ecsion** [comment]
done
