### ISSUE TITLE
Leveraged Fund reporting call

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Bug-Tracker#106]
Needs some modification:
Needs a Title (text) field - best location would be between "Project Number" and "Type"

Type should be a picklist with these two items to choose from: Managed, Influenced

Primary Focus Area should be a picklist - same one as for entering project information

Instead of one "Period" field we need separate fields for "Start Date" and "End Date"

![image](https://cloud.githubusercontent.com/assets/17415806/13751020/853bfdc8-e9de-11e5-9dc2-143e0da6136a.png)

**Comment by ecsion** [comment]
We have made these changes for you. You can easily do this yourself by editing the form. The pick lists has to be manually configured (In 2.0 we will allow predefined pick lists)
