### ISSUE TITLE
Re-setting password if user forgets

### ISSUE THREAD

**Issue by schalifoux** [ecsion/eSeaGrant-Bug-Tracker#109]
If the user selects "Forgot Password" from the login screen, enters their info, then follows the link in the e-mail they receive, the screen the user is brought to has MIT's logo, and the spacing is a little funny.

![image](https://cloud.githubusercontent.com/assets/17415806/13751476/c5664492-e9e0-11e5-96d0-7a7aacc36e4d.png)

**Comment by ecsion** [comment]
fixed.
