### ISSUE TITLE
Data Migration: Impacts & Accomplishments

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#11]
Erroneous PI. **Resolved.**
	Project title not resolved: which one, Kate? At top, just below “Reporting Call: 2014-02-01 to 2015-0131” or in I&A list’s first column (if latter, is it practical to have full title?).
	Missing relevance, response, results. **Resolved.**
	**Others issues:** 
	a) Why are there two records for same report year? This is so for multiple project reports (e.g., R/LME-6, R/OCEH-9).
	b) I&A Response and Results have same info: “Included with Relevance (Legacy Migration)”—this is because response and results were included with relevance text in original database. Moving forward, I infer we can now input this info in it’s appropriate fields instead of grouping all in one. **Resolved.**

**Comment by ecsion** [comment]
done.
