### ISSUE TITLE
Data Migration: Reports Field Errors

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#12]
1. Narrative listed wrong PI. **Resolved.**
2. Kate commented on narrative title not being original name of narrative file. Not sure this matters, but the narrative title is still “R/LME-6 Report.” Having full title seems impractical given available space; but would be helpful to have full title in the “Report Title” at the top of the page as well as the code (e.g., R/LME-6). **Pending**

**Comment by ecsion** [comment]
fixed.
