### ISSUE TITLE
Profile anomaly

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#21]
When we go to my preferences, don’t actually change anything, but try to hit “save” and get a message that the email address already exists—cannot move off of screen without canceling.
Note that this doesn't happen when we change a different field—seems limited to email field.
BTW: what does "refresh permissions" do (we know what it means but what does it actually address)?

**Comment by ecsion** [comment]
Refresh permissions link is useful when Project PI changes. The permission occasionally does  not auto-refresh and so we have provided manual refresh permission just in case. Don;t think you will have a need   to use it.

**Comment by mgduke** [comment]
No, I wouldn’t think so. But ya never know, right? I had forgotten you had already that we had covered the possibility of PI’s changing. Good!

 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator  |  Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>

**Comment by ecsion** [comment]
done.
