### ISSUE TITLE
Reports: Data repeated (may be unique to WSG instance)

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#25]
There are many instances where data are repeated twice - e.g., R/SFA-1 2014 annual report - update - impact/accomp statement repeated twice; tools, tech, info services repeated twice; meetings, workshops repeated twice; economic impacts repeated twice; leveraged funds repeated twice.

Note: I infer this is due to multiple re-importing of the dbase after code updates. Not sure whether this is best resolved when we're ready to launch or what.

**Comment by ecsion** [comment]
done.
