### ISSUE TITLE
Reports: Impact & Accomplishments Statements—Titles missing

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#26]
Impact and accomplishment statements: Titles do not appear to have been migrated appropriately - e.g., R/SFA-1 2014 annual report - update - impact/accomp tittle is “R/SFA-1 Report” but in the old system title is "Washington Sea Grant research probes effects of ocean acidification and warming on farmed and wild mussels in Puget Sound. Please refer to xSG and eSG screenshots for comparison (note eSG title has full English title, not the report #.
![screen shot 2016-02-18 at 11 05 52 am](https://cloud.githubusercontent.com/assets/17168836/13155870/b5e5f586-d634-11e5-890e-75862aac14af.png)
![screen shot 2016-02-18 at 11 07 22 am](https://cloud.githubusercontent.com/assets/17168836/13155874/ba30ed9e-d634-11e5-8808-40c155520746.png)

”

**Comment by ecsion** [comment]
added titles.
