### ISSUE TITLE
Reports: Student info missing (inconsistent)

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#27]
Student info is missing in R/SFA-1 2014 annual report (Update):  The student info record for Emily Roberts is blank for all fields except degree, but in the old system the info is not missing.The odd thing is that the few other student records we checked were not missing info. Reference screenshots for xSG and eSG:

![screen shot 2016-02-18 at 11 10 24 am](https://cloud.githubusercontent.com/assets/17168836/13156041/67acc498-d635-11e5-98be-ed695da08507.png)
![screen shot 2016-02-18 at 11 09 40 am](https://cloud.githubusercontent.com/assets/17168836/13156042/67cd210c-d635-11e5-9fc9-96aa38554a7d.png)

**Comment by ecsion** [comment]
Legacy data has duplicate records for Emily Roberts with the same email that is throwing off the import. Ecsion will not be able to fix data issues.

**Comment by mgduke** [comment]
Acknowledged. Can you provide any recommendation on how to fix on our end? For example, would it be better to fix it in the old eSeaGrant and reimport, or should we do the fixing in xSG?
