### ISSUE TITLE
People: Student records: no link to associated projects?

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#28]
In eSG: student records link to associated projects - that does not appear to be the case in the new system. Is this an oversight (i.e., we didn't tell you about this), or is that data available and just needs to be called? Compare screenshots of xSG with eSG's People/Students/Projects tab.

![screen shot 2016-02-18 at 11 12 27 am](https://cloud.githubusercontent.com/assets/17168836/13156162/f8610828-d635-11e5-8c95-382632a4275a.png)

<img width="996" alt="screen shot 2016-02-18 at 11 52 12 am" src="https://cloud.githubusercontent.com/assets/17168836/13156219/33fdd96a-d636-11e5-85e1-aae332941d02.png">

**Comment by ecsion** [comment]
This is a data issue with Washington Data. Emily has 2 records in the students in Washington with the same email. That is causing an issue with the import.  We won;t be able to fix data issues in the old eSG system.

**Comment by mgduke** [comment]
Deepak, I think that's a separate issue and we acknowledge that errors or situations in the old dbase will cause problems and may be solely up to us to resolve. But in this case, your interface depicted above has no field to display links to projects the student worked on. 

**Howsoever(!)**, what we failed to realize was that the 2nd link in the left-margin, "eSeaGrant History," _does_ show one of Emily's projects, and this page also works for other students. So I think we're good to go with one request: would it be possible to make the projects link to the main projects page for _that_ project? For example, Emily Roberts' project listed under "eSeaGrant History" (R/SFA-2) would link to:

http://esg.wsg.washington.edu/index.php?module=Projects&view=Detail&record=1995&mode=showDetailViewByMode&requestMode=summary&tab_label=Project%20Information
