### ISSUE TITLE
General Navigation (Usability)

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#29]
When you are in a report record and you drill down into, e.g., the detailed impact/accomp or students pages, there does not appear to be any way to navigate directly back to the preceding page (i.e., within the context of the associated report). This makes for very cumbersome navigation.

**Comment by ecsion** [comment]
Please use browser back button to navigate back.

**Comment by mgduke** [comment]
OK, that goes counter to typical usage, but that's fine. Are there any caveats about this, however? Or is backing out perfectly fine as long as we remember to save any changes on a page first?

Also, are you saying that providing live-link breadcrumbs is not feasible or more just beyond reasonable scope and thus would be a new feature request requiring additional billing?
