### ISSUE TITLE
Unknown RC added to People

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Bug-Tracker#3]
We noticed that a new RC signed themselves up on our web site: priyanka.tawde@gmail.com. There is no affiliation attached to this person.
Is this an Ecsion employee? If not, then we do not know what is happening and how this profile was added.
If this is an Ecsion employee, can you please let us know beforehand that this is occurring or ask them to add their affiliation? Otherwise, we will delete their profile.

**Comment by ecsion** [comment]
This is ecsion profile. We will add affiliation in the future.
