### ISSUE TITLE
Data Migration: Reports: Student Info Missing (part 2)

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#31]
The "Involvement with Sea Grant" field is populated in eSG but not in xSG. See screenshots.

![screen shot 2016-02-18 at 11 16 23 am](https://cloud.githubusercontent.com/assets/17168836/13156760/eae5ae26-d638-11e5-8667-ef998b9644d0.png)
![screen shot 2016-02-18 at 11 16 35 am](https://cloud.githubusercontent.com/assets/17168836/13156761/eaeb8b7a-d638-11e5-84cb-7f519d7002a6.png)

**Comment by ecsion** [comment]
done.
