### ISSUE TITLE
PI Discrepancy (possibly WSG-centric)

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#32]
Deepak notes there are 800+ PIs in our records but our old system suggests otherwise. This may at least partly related related to projects not having PIs. For examples:
	Pacific Northwest Outreach…
	Knauss Fellow - Molly Jacobs
	Partitioning Multiple Pressures Impacting Southern Resident Killer Whales
What should we do about this? We can’t ignore projects just because they don’t have a PI (note at least some of these do have a project ID that includes the PI name ["Partitioning Multiple Pressures" noted above shows “Wasser_8962”] but others have “0” for project ID). I know this arose in the old system and came along for the ride with the migration. Not sure how best to address this.

**Comment by ecsion** [comment]
This is data scrubbing issue which is not included in Data Migration. Let's have a separate chat on options.

**Comment by mgduke** [comment]
OK, let's chat. It would to know whether this is something that must be resolved before opening the 2015-16 reporting call and could wait for us to do over a longer time period. Also, while I some doubt this, I'd be interested in whether we'd be better off "manually" (i.e., not with queries) fixing this in MySQL (i.e., via phpmyadmin), or possibly contracting with Ecsion separately to help resolve.
