### ISSUE TITLE
Reports: Searching Anomalies

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#34]
1. Searching PI yields wrong results:
Search for Kahn = no record but she is in fact a project PI.
2. When searching for “Not submitted” in Report Status, we get odd results, possibly self-caused:
        Brand-new report created today shows up.
        Three reports belong to a reporting call that we deleted don't show up (but we can't delete those reports).
I include some further elaboration from Kate:
There are three not submitted reports associated with project # E/H-2014-Graziano.  Two issues:
1. They do not appear in the “reports” menu.  (And if you search for “not submitted” nothing comes up, even though these three not submitted reports are in the system.)
2. They are associated with report calls that we have since deleted.  So now, even though you have made it so that we can delete reports through the reporting call interface (thank you!) - we cannot access these three reports through that interface that would permit deleting them… so we still cannot delete these three reports.
Incidentally, I would be in favor of making it so that you cannot delete a reporting call that has reports associated with it…

**Comment by ecsion** [comment]
Marcus, We don't follow the issue. Please provide screenshots.

**Comment by mgduke** [comment]
Hi, there: You appear to have fixed the first issue (Kahn not appearing); I need to confer with Kate to see if the remaining issues listed in this ticket persist.

 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator  |  Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>
