### ISSUE TITLE
Data Migration: Report: Partners issue and question

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#35]
When adding partner in a report: If you select an existing partner from the list (e.g., Washington State Department of Ecology), the scale and type fields automatically populate (as they should for an existing partner). But then when trying to save, it says those two fields are required and will not let you move on without reselecting the correct responses from the drop down list (those responses have been the same other than case has differed).

And, the "Partners this period" page still includes 5 other fields (reporting call, PI, project #, reporting start/end dates) that we really don't need. However, we could use the "Notes" field if that were possible (truncation of overly verbose notes is fine, not that we ever have that…!).

![screen shot 2016-02-18 at 1 58 26 pm](https://cloud.githubusercontent.com/assets/17168836/13160552/d4c6a6fe-d64c-11e5-992f-2a18f7d2ffb4.png)

**Comment by ecsion** [comment]
done.

**Comment by mgduke** [comment]
Deepak, the first issue listed above is mostly ok, other than it seems odd that the Scale field auto-populates when creating a new Partner, but the Types field does not. Can you just set Scale <option> to "Select an option," just as you've done for Types, please?
