### ISSUE TITLE
Report: "Save" versus "Add" nomenclature

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#36]
Minor issue that's common across all custom forms with multiple entry capability: the "Add" button is just a bit confusing—e.g., if you only have one entry, it's not intuitive that Add actually saves it. Can we change the word to "Save"?

![screen shot 2016-02-18 at 2 11 11 pm](https://cloud.githubusercontent.com/assets/17168836/13161180/efbdb2aa-d650-11e5-8771-a3a30ac229bd.png)

**Comment by ecsion** [comment]
fixed.
