### ISSUE TITLE
Report: Metrics page layout issues

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#38]
Metrics page layout is not really working: Note this issue is based on newly entered data.
1. metric titles are repeated unnecessarily
2. instructions are not appearing (even though I know they are there)
3. order of metrics does not match the “sequence” order listed on the page where you create the metrics question (e.g., volunteer hours has sequence order of 7 on the page where I created that, but is appearing as metric # 9)
4. why are there blue numbers in the little boxes - not sure I understand how/why those are relevant to the person filling out the report? Can you remove these or is there some backend purpose for having them?
5. Nice to have: ability to change the field names (e.g., “Value” and “Note”). Not a deal breaker, but would be nice…

![screen shot 2016-02-18 at 2 18 49 pm](https://cloud.githubusercontent.com/assets/17168836/13161371/143a31ac-d652-11e5-9ae2-fa6696694d88.png)

**Comment by ecsion** [comment]
Currently we don't support sequence numbers for metric questions.

The styling issue has been fixed.

**Comment by mgduke** [comment]
Only one thing remains, then: occasionally, I see a period on a separate line between the first metric label and the value label (screenshots attached).

![screen shot 2016-02-26 at 1 03 04 pm](https://cloud.githubusercontent.com/assets/17168836/13365400/9f591c7a-dc89-11e5-863f-3ac4d5631f9e.png)
![screen shot 2016-02-26 at 1 04 13 pm](https://cloud.githubusercontent.com/assets/17168836/13365401/9f7656e6-dc89-11e5-893a-00da02c8e29e.png)
