### ISSUE TITLE
People: Student data and fields missing

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#41]
In the old eSeaGrant interface's People/Students/Contact info interface, students had some different fields compared with investigators et al. (e.g., advisor). In the new system, there seems to be a one-size-fits-all "Profile and Contact Info." Where did the unique student fields go? Can we have them back? Kate says its important information.

Kate notes that some of the presumably missing fields in the people record are in the Project Report/Students Supported/Students Supported Details and we wonder if this was deliberate (i.e., not duplicate fields across different pages). If so, ok, but it would help to more easily get to the student supported details page from People record. 

Please see also ensuing issue (similar w/more detail)

**Comment by ecsion** [comment]
As you correctly stated, we don;t have all the fields in the new eSeaGrant. So possibly we can put this data in a notes field.

**Comment by ecsion** [comment]
done
