### ISSUE TITLE
Data Migration: Student Supported Details data missing

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#42]
Please compare screenshots to note that fields in the new interface with no data actually do have those data in the old interface.  NOTE: Deepak, if it would be useful to know the actual MySQL fieldnames from the old system when we present such issues, please let us know. It's somewhat laborious gather these (I can't just select a bunch of fields, I'd have to type each field anew here), but it's do-able and if it helps you a lot, we'll do it.

<img width="1039" alt="screen shot 2016-02-22 at 1 30 11 pm" src="https://cloud.githubusercontent.com/assets/17168836/13233427/7a3745da-d968-11e5-8ee8-bc68e6a3bb0b.png">
<img width="1005" alt="screen shot 2016-02-22 at 1 30 20 pm" src="https://cloud.githubusercontent.com/assets/17168836/13233428/7be02fd2-d968-11e5-9867-6a014e20b73d.png">

**Comment by ecsion** [comment]
Looking into this. If you can provide the exact field names in mySql, that would be very helpful.

**Comment by ecsion** [comment]
done.
