### ISSUE TITLE
Student degree date

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#43]
In the old system, under People/Students/Contact Info, there are two fields for degree date: Anticipated and Actual. The new system only has one field, which is not in the people profile, only in "Student Supported Details" ("Degree year"). These two fields are very useful for student tracking. Can we get this distinction in degree year back somehow (anticipated vs. actual)?

**Comment by ecsion** [comment]
As you correctly stated , we only have one field in People, Called Degree Year which was  what the tech committee requested. You can put anticipated vs actual in the notes field. Also if you want to record multiple degrees for a student, you can also do it  in notes field.
