### ISSUE TITLE
Reporting: Publications

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#44]
Please do not require publication number or abstract fields. Also, when adding a new publication, the text above the table containing the fields we enter data into shows an odd string after "Editing:" — that is, "AddMetric-100".

<img width="1261" alt="screen shot 2016-02-22 at 1 58 09 pm" src="https://cloud.githubusercontent.com/assets/17168836/13234254/9b88a7fc-d96c-11e5-802e-3d09d8035ce4.png">

**Comment by ecsion** [comment]
fixed.
