### ISSUE TITLE
Issue #35 continued: Partners scale/types fields

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#45]
In addition to having to reselect the scale and type fields in order to save a partner in a Report entry, under Report Calls/Partners, we note that Scale and Types data "disappear" when we click the edit button (i.e., just says "Select an Option"). 

<img width="854" alt="screen shot 2016-02-22 at 2 12 09 pm" src="https://cloud.githubusercontent.com/assets/17168836/13234615/619469bc-d96e-11e5-87ca-545d1598754a.png">
<img width="1238" alt="screen shot 2016-02-22 at 2 11 58 pm" src="https://cloud.githubusercontent.com/assets/17168836/13234619/679bcca6-d96e-11e5-895a-cc3a20fade3d.png">

**Comment by ecsion** [comment]
fixed

**Comment by mgduke** [comment]
Hmmmm; partly fixed (data don't disappear), but we still have to reselect the scale and type fields in order to save the record.

**Comment by mgduke** [comment]
Almost: Now only the "Types" field requires us to reselect an option before we can save it.
