### ISSUE TITLE
Projects/Reports: Report Call lists wrong data

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#46]
In Projects/Reports, the table listing the records shows the "Report Call" field, which is the same for every report (so not very useful in this context)—would be much more helpful to list the reporting call here??  BTW - what is the "report call" field for—for example, looking at 2nd screenshot, you have "Report Call" and "Reporting Call" fields—we're confused; what's the difference?

<img width="1198" alt="screen shot 2016-02-22 at 2 24 11 pm" src="https://cloud.githubusercontent.com/assets/17168836/13234997/774780f8-d970-11e5-8f14-4ca442b3dde7.png">
<img width="883" alt="screen shot 2016-02-22 at 2 24 42 pm" src="https://cloud.githubusercontent.com/assets/17168836/13234998/775dde34-d970-11e5-8f20-c1a1b4e07c65.png">

**Comment by ecsion** [comment]
fixed.

**Comment by mgduke** [comment]
Agreed but maybe the Report Information label under **General Information** should be changed to something like "Report Number" to further differentiate from "Reporting Call" under the **Reporting Call & Project Name** section.

**Comment by mgduke** [comment]
Correction to my comments: Under **General Information**, please change "Report Call" to "Report Title." In the sidebar for **Reports**, please change "Report Call Info" to just "Report Info".
