### ISSUE TITLE
Partners list issue 

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#47]
We have no idea how/why partners got so off base, but many reports (possibly all) have incorrect partners listed. There are many many partners, so we're not even sure how to go about telling you what to do, but if there were any way to determine whether your migration query was the cause of this, and fix it, that would be most helpful; repairing it "manually" will be extremely laborious. We admit we need to clean up the partners anyway, but before we go for the nuclear option and have you delete all the partners and we would manually re-enter, we are hoping you might have some way to fix the mismatches. 

We provide an example screenshots of partners listed for the same report in our old interface and in xSG, which shows that the partners are totally different between interfaces:

<img width="1000" alt="screen shot 2016-02-22 at 2 41 31 pm" src="https://cloud.githubusercontent.com/assets/17168836/13235385/75bf8ff8-d972-11e5-8577-d4c25f90c08e.png">

<img width="964" alt="screen shot 2016-02-22 at 2 41 47 pm" src="https://cloud.githubusercontent.com/assets/17168836/13235388/7a158b8e-d972-11e5-8005-0277dbf2b44f.png">

**Comment by ecsion** [comment]
fixed.
