### ISSUE TITLE
Partners question

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#48]
When you make edits to an already existing partner in the master partner list (in Report Calls) - what happens to previous uses of that partner (e.g., in reports) - do those edits carry through (i.e., change to partner name or change to scale or type)?

**Comment by ecsion** [comment]
There are two modules (think of them as tables) The 
1. Partners master list
2. Partner this Period.
During reporting, the PI can select from Partners Master List via autocomplete or enter a partner that is not in the master list. What ever he does (selects from Master or enters a new one), it only affects the Partners this period. This means that if you later change the master list data, the report does not change as it shouldn't. Hope this clarifies.

**Comment by mgduke** [comment]
Thanks. Say, is there any way to cc someone when I submit tickets so that Kate can get notifications of the submittal and your responses?

 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator  |  Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>
