### ISSUE TITLE
Draft emails lost

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Bug-Tracker#5]
When you send an email to someone, anyone, and click “Save as draft,” the email completely disappears. We don’t where to find the saved draft.
![email_draft_webshot](https://cloud.githubusercontent.com/assets/17169131/13085162/b0fffd18-d491-11e5-900e-13db25731dfa.png)

**Comment by ecsion** [comment]
We don't have draft save capability so we are removing the Save As Draft button.
