### ISSUE TITLE
New Login Interface

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#50]
The new login page looks very good! Very minor requests (style):

1. Please style the non-active tab to make its text more readable (e.g., make font color in gray tab #fff). 
2. Please style the tab a:hover and a:active properties to make onFocus/mouseOver more apparent (currently, the very thin white line that appears on hover or active is hard to see—maybe try the dark blue color used for the "Log in" page).
3. On the Register tab, please change "log-in" to "login" in the 2nd bullet.
4. Login tab: Please add colon after "Welcome to WSG eSeaGrant".
5. You might want to correct the typo, "Carengie," in your Ecsion attribution under the login div. Also, suggest adding commas after "Ecsion" and "Inc." — "Ecsion, Inc., 103 Carnegie…"

BTW, thank you for not making my email address a mailto link. I'm just learning about accessibility and usability issues regarding this and the consensus is against using mailto links.

**Comment by ecsion** [comment]
done.
