### ISSUE TITLE
Critical: Add Project Issue

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#55]
Kate added a new project this morning (A-Adams), but it is not showing up on the projects list and thus she cannot add it to a reporting call (because it does not show up there either).  

However, if she goes to the people record associated with the PI (Jeffrey Adams) and goes to eSeaGrant History - it shows up there… but you can’t click through to it from there (we assume that's because you just haven't gotten to linking that to the project, which we discussed on 2/23/16).

**Comment by ecsion** [comment]
fixed.

**Comment by mgduke** [comment]
OK, project appears, but (1) I tested by adding another project that I now want to delete, but when I click the delete button and follow the prompt, the project does not get deleted.

Also, is it deliberate that once a project is published, "Action" options are no longer available? Seems we'd want the ability to delete a project, no?
