### ISSUE TITLE
Reporting: Misaligned radio buttons

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#56]
We've found that radio buttons (yes, no) in custom forms have a small misalignment problem: Instead of a button, then label, then button, then label, both buttons appear first, then "Yes" and "No". This first was observed in a custom Tools, Technologies, Information Services / Sea Grant Products" custom form created by Kate, but she also noted the same problem in the Community Hazard Resilience custom form. Screenshot attached for your reference.

![screen shot 2016-02-24 at 11 35 12 am](https://cloud.githubusercontent.com/assets/17168836/13299079/665ee8e2-daee-11e5-8798-c7d3705c7d2b.png)

**Comment by ecsion** [comment]
fixed.
