### ISSUE TITLE
Reporting: Cover page

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#58]
Under Part II - Documentation: Having looked at an MIT coverpage from their xSG app, I'm under the impression the various items reported (e.g., Impacts & Accomplishment, Meeting…, Publications, etc.) should appear on the cover page. Using the 2014-2015 Hershman Fellow Final Report/Project E/H-2014-Bogeberg, I note that some items do appear on the cover page (e.g., publication title) and some don't (e.g., Tools, Technologies, Info Services…; Economic Impacts; Community Hazard Resilience). MIT's on the other hand seemed to include many of these.

Also, I note for "Documents:" there's no space between that label and the ensuing data.

I attach a sample of MIT's output fyi.

[MIT-report-coverpage.pdf](https://github.com/ecsion/eSeaGrant-Bug-Tracker/files/146839/MIT-report-coverpage.pdf)

**Comment by ecsion** [comment]
Spoke to Kathy Zengotita and based on her feedback, we have now simplified the coverage.
