### ISSUE TITLE
Reporting: Sidebar not always indicating data exist

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#59]
Referencing call 2014-2015 Hershman Fellow Final Report, project E/H-2014-Bogeberg: 

I infer the red and green dots for the Reports sidebar (e.g., Impacts and Accomplishments, Partners this Period, Meetings, Workshops, Presentations, etc.) indicate whether any content has been entered into these forms—correct? However, I note that only the Partners form has a green dot, but all other forms that have data show a red dot.

**Comment by ecsion** [comment]
The green dot/red dot is meant for the PI to keep track of what he as completed. So for instance, he can have no data in a particular question and mark it as completed without entering any data whatsoever. I think e may have erred in the data migration and left some questions as not completed, when they really are. We can fix this.

**Comment by mgduke** [comment]
OK, thanks.
