### ISSUE TITLE
Project Document flow issue

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Bug-Tracker#6]
When in Projects--we open a project > choose Project Documents-->choose Project Document Details. We find it difficult to get back to the list of project documents specific to that project. The left menu tabs specific to the project (e.g., Project Information, Comments, Reports, etc.) disappear and are replaced by just the General Information tab. When you click the breadcrumb trail “Project Documents” link, it takes you back to all project documents across all projects, instead of back to the specific project on which you are working. I can send you a video clip. -Cathy

**Comment by ecsion** [comment]
fixed. Please verify.

**Comment by mcbridec** [comment]
Yes, fixed. Thank you so much!
