### ISSUE TITLE
PickList Editor: Prevents "special characters"

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#60]
I tried to add a record to our Publications picklist that had commas in it and got a red alert saying:

Special Characters like < > " , are not allowed.

Really? No commas?? Please change this to allow standard punctuation. Special chars, however, are not required.

**Comment by ecsion** [comment]
Marcus, what are you trying to add?

**Comment by mgduke** [comment]
Commas.

 <https://wsg.washington.edu/>	
Marcus Duke
Editor/Computer Systems Administrator  |  Washington Sea Grant <https://wsg.washington.edu/>
College of the Environment  |  University of Washington
T 206.685.0171 <tel:206-685-0171>

**Comment by ecsion** [comment]
done.
