### ISSUE TITLE
Reporting: Publications: Request Add "Peer-reviewed?" radio button

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#61]
SCRATCH THIS: Just checked and see you already added this a while ago. My bad; sorry!

_Our publications categories are numerous and it can get quite complicated to account for all of these in the context of whether the publication was peer-reviewed or not (e.g., we have multiple instances of duplicate entries of publication types with one being "peer-review" and the other "non-peer-review"). It would be much easier to remove "peer-review" from the pick list entirely, provided you could put the following REQUIRED radio button on the Publications entry page:

Peer-reviewed?  ° Yes  ° No_

**Comment by mgduke** [comment]
Oh drat: Just realized that a radio button is the better option because I need to REQUIRE people to indicate whether a publication was peer-reviewed or not. So please do change the check box to a Yes/No radio button pair.

**Comment by ecsion** [comment]
done.
