### ISSUE TITLE
Reporting: Issues with making new call from previously existing call

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#62]
From Kate:
I tried making a new reporting call from an existing reporting call (“+new from template or call” button) as an attempt to “fix” the metrics selected in my 2014 annual report - staff call (i.e., I selected all the metrics in the system thinking they were the new ones I had entered before realizing the ones I had entered had been blown away…)

On the surface, seems like this should have worked - 
- go into the new call (2014 annual report - staff - new); go to select metrics page; there is a “delete” button next to each metric because the call has not been published 
But when you press the delete button and say yes you really want to delete, nothing actually happens…  (i.e., not deleted)

Also - the deadline and reporting dates from the original call do not stick in the new call that you made (although it looks like they are there until you hit the “save” button…

**Comment by ecsion** [comment]
fixed.
