### ISSUE TITLE
Formatting: Bold not showing on instructions

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#66]
See following for example where boldface is not showing in first line of each instruction chunk:

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=17316&mode=showInstructions&tab_label=Instructions

<img width="1285" alt="screen shot 2016-03-01 at 1 04 54 pm" src="https://cloud.githubusercontent.com/assets/17168836/13441866/546fe838-dfae-11e5-8623-ae8d0092810d.png">

**Comment by ecsion** [comment]
done
