### ISSUE TITLE
Request Instructions Sequence Matches Menu (Tab) Sequence

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#67]
Nice to have: Have instruction components appear in the same sequence that the left-margin menu appears. 

This "tab order" also is true for the Project Summary.

**Comment by ecsion** [comment]
Sections have to remain intact and so we have fixed the order within a section. However, Metrics is a section and will appear separately and out of order. If we need to do more, then this is a 2.0 thing.
