### ISSUE TITLE
Orphaned Reports: Please delete

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#69]
Deepak, here's the URL-query link to the page with the three orphaned reports (i.e., these records have no data in the fields on the below page), along w/a screenshot:

http://esg.wsg.washington.edu/index.php?module=Projects&relatedModule=Reporting&view=Detail&record=15869&mode=showRelatedList&tab_label=Reporting

<img width="1064" alt="screen shot 2016-03-02 at 12 05 37 pm" src="https://cloud.githubusercontent.com/assets/17168836/13473661/30bbbe3c-e06f-11e5-90ba-6efc0cab9c81.png">

**Comment by ecsion** [comment]
Marcus, We want ot fix the root cause. Could you please provide the exact steps on how these orphaned reports issue happned.

**Comment by mgduke** [comment]
Deepak, did I give you enough clarification in the email response to your question? In case you didn't see that, I copy here:

These were from reporting calls that we deleted. 

We created a reporting call - added project - published - started report - then deleted the reporting call - which created the orphaned reports. 

If I understand correctly, the system now should not allow this to happen.  I.e., you should not be able to delete a reporting call without first deleting all of the reports therein. 

Does that make sense?

**Comment by ecsion** [comment]
deleted.
