### ISSUE TITLE
"Fellow" hidden when attempting to add to a Person profile

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Bug-Tracker#7]
People: When “Fellow” is added to the Picklist under eSeaGrant History, it does not then appear for use anywhere later (i.e., not there when trying to add it to a Person's profile). Not all of our Fellows are students and not all consider them PIs, so we'd like to use Fellow as a type.

**Comment by ecsion** [comment]
Fixed.
