### ISSUE TITLE
Reporting Call Additions Don't Appear for Previously Published & Started Reports

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#70]
After a report call has been published to projects and the reports have been started, we need new custom forms, metrics, etc. added to the report call to appear in those previously started reports. At present, we have to delete the reports and republish them to have the new forms appear in them. We're thought we had already talked about this and you were working on it. Is this something that will be resolved with tomorrow's update? This is a critical issue.

**Comment by ecsion** [comment]
done.
