### ISSUE TITLE
Urgent: Custom form labels character limit?

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#71]
Kate is trying to set up a reporting call today and, in the process of adding an Impacts & Accomplishments custom form that has a "Goals" section with 11 check boxes, she's being constrained to only three checkboxes on saving it (see link below). We suspect this is caused by a char limit for the <options> text because she tried creating 11 checkboxes with much briefer option texts in another part of the form, and that worked.

Hate to push, but she needs to publish this call today, so this needs to be fixed right away, if possible. 

http://esg.wsg.washington.edu/index.php?module=MultipartQuestionStem&view=Edit&record=17403&showList=true

**Comment by mgduke** [comment]
Update: we were able to add another option to Goals, but I hesitate to add any further options because we are unable to remove them (we click "Remove Option", get the popup "Yes/No" prompt, click "Yes" but the option remains).

**Comment by ecsion** [comment]
fixed.
