### ISSUE TITLE
Custom form checkboxes: formatting a bit off

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#72]
Check boxes & labels added to a custom form are running continuously instead of starting new line with each new checkbox. Screenshot attached; example link:

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=17447&mode=showMultiQuestionStem&QuestionId=17403&tab_label=Impacts%20and%20Accomlishments&tab_label=Impacts%20and%20Accomlishments

<img width="999" alt="screen shot 2016-03-03 at 1 36 23 pm" src="https://cloud.githubusercontent.com/assets/17168836/13510408/291265ce-e145-11e5-9ffc-faf5134268cf.png">

**Comment by ecsion** [comment]
fixed.
