### ISSUE TITLE
Reporting: Student supported degree year field mix-up

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#73]
In the Students Supported form, for Degree Year, we entered 2017. However, when we check "Submission Preview," the Degree Year is listed as "Degree date:" and the year is instead listed as today's date, "03/03/2016". See URLs:

Student Supported Form:
http://esg.wsg.washington.edu/index.php?module=StudentsSupported&view=Edit&record=17449

Submission Preview:
http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=17447&mode=showFullReport&tab_label=Submission%20Preview&tab_label=Submission%20Preview

**Comment by ecsion** [comment]
fixed.

**Comment by mgduke** [comment]
Agreed but please change "Degree date" to "Degree year" on Submission Preview. Thank you!
