### ISSUE TITLE
Reporting Instructions: Fixed Form Modules Showing When Not Selected

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#74]
Fixed forms modules are included even when that module has not been selected for the reporting call:

Setup Report Call:
http://esg.wsg.washington.edu/index.php?module=CallReporting&view=Detail&record=17409

Instructions within the Report
http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=17447&mode=showInstructions&tab_label=Instructions&tab_label=Instructions

**Comment by ecsion** [comment]
fixed.
