### ISSUE TITLE
Reporting Instructions: Instructions Don't Appear on Fixed Modules

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#75]
The instructions for fixed modules (e.g., publications, narratives, partners, students) only show up on the “Instructions” page in a report - they do not currently show up on the page where an investigator actually fills out that information. It's important that they show up in both places (like all of the other instructions - e.g., for metrics and for custom forms).

**Comment by ecsion** [comment]
done.
