### ISSUE TITLE
Text changes to "$AutoSystemEmails Send mail to PI after UserTask Create" template

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#76]
For the "$AutoSystemEmails Send mail to PI after UserTask Create" template

1. Change email title to: 
	New Washington Sea Grant Report Assigned—$AutoSystemEmails-TaskSubjectTitle$

3. In the message:
	Change first sentence to:
		A new reporting task has been assigned to you by eSeaGrant (please use same link)
	
	In Details table:
		Change “Task” to “Report” for “Task Type” and “Task Title”
	
4. Signature should be:

Thank you,

Washington Sea Grant

**Comment by ecsion** [comment]
done.
