### ISSUE TITLE
Permission denied on project 

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Bug-Tracker#78]
When we click on Katelyn Bosley's project we get a "permission denied" message. This is not occurring when we choose other projects. We are signing in as an RC.
Project #: R/S E/INT-122
![2016-03-08_0828_oregon fw](https://cloud.githubusercontent.com/assets/17169131/13608192/87e528b8-e508-11e5-8459-f480fcd8cbd4.png)

**Comment by ecsion** [comment]
fixed, please check and reopen this issues if not fixed.

**Comment by mcbridec** [comment]
Seems to be fine now - thank you!
