### ISSUE TITLE
Exporting the Projects list

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Bug-Tracker#8]
First, when an RC exports records (create a pdf) to get a list of Projects from the Projects tab, there could be more information supplied per project. We could use this list to relay basic project info to management we had these headings when we “export” and “export all”: Project #, Project Title, Funding Start, Funding End, Primary Award #, Primary Focus Area. Plus, it would match what was in PIER under “Funding”.
 
Second, can we please change the page title/header on that exported file to say something like “eSeaGrant Projects”? To be more efficient for us, the current title needs to change if possible.

**Comment by ecsion** [comment]
done.
