### ISSUE TITLE
Report Summary Field Order: Small Change

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#84]
Referring to below page, we note that under Impacts & Accomplishments, the Comments field text appears before the Recap field text. These two fields should be revered, please.

http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=3787&mode=showFullReport&tab_label=Submission%20Preview&tab_label=Report%20Summary

**Comment by ecsion** [comment]
fixed.
