### ISSUE TITLE
Report Summary issues with old (migrated) reports

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#85]
Please refer to "2014 annual report - completion" for Daniel Grunbaum, project #R/OCEH-6:
http://esg.wsg.washington.edu/index.php?module=Reporting&view=Detail&record=3787&mode=showFullReport&tab_label=Submission%20Preview&tab_label=Report%20Summary

From what Kate can tell, the data migration looks okay, but weird things are displaying in the report summary:

1. Two blank students showing up before the two that are actually included in his report on the "Students Supported" page.
2. Both students (Tobin and Coyle) have “(New Student)” next to their name, but they are both continuing students (as indicated by data on the student supported page)

**Comment by mgduke** [comment]
BTW, we noticed that when editing the student supported record, the "New or continuing?" dropdown menu was set to "Select an option", and we thought this might be the issue. (Also, we noticed the original entry was "cont" in the "Student Supported Details" view (before clicking edit). However, on changing to "continuing" (which then appeared in the "Details" page), we note the report summary still shows that student as "(New student)".

**Comment by ecsion** [comment]
fixed.

**Comment by mgduke** [comment]
Item 2 above was fixed for one (Elizabeth Tobin) but not for Owen Coyle. I corrected that and this leads me to ask whether we need to strategize about some of these issues: That is, when is it more appropriate for you to correct something and when should we just fix it ourselves?
