### ISSUE TITLE
System email: what does "expiry date" field mean?

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#86]
http://esg.wsg.washington.edu/index.php?module=EmailTemplates&view=Detail&record=50

We are unsure what the meaning of "Expiry date" is in the system email for "Task started." How does this differ from "Due date"? Prima facie, this field seems unnecessary, but … ?

**Comment by ecsion** [comment]
We will remove in the new templates that we are creating (in about a week).
