### ISSUE TITLE
System email part 2: New user email confusion

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Bug-Tracker#87]
http://esg.wsg.washington.edu/index.php?module=EmailTemplates&view=Detail&record=56

Who does this go to? When is it activated? Could this be generated by investigators who are adding personnel to an RFP or report? Or is it just generated by administrative staff?

**Comment by ecsion** [comment]
Currently this email is generated by administrative staff and goes to him/self or herself as a confirmation. Trigger is creating a new user (a new entry people is not a new user and so no email is generated when add a people entry).

A different email is generated for the user being created that uses another template (not this one). 

We are changing this and will make the emails common and the RC will be cc to the email that goes to newly created user. Expect this fucntionalitynmnnabout a week.
