### ISSUE TITLE
Reporting Call assignment issues

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Bug-Tracker#9]
Created new reporting call (2014-2015 Hershman Fellow Final Report): set reporting start date to 10/1/14; set reporting end date to 9/30/15; set deadline to 3/31/16. However:
1. Under assignments (for admin): close date and due date are both set to reporting end date (9/30/15)
2. For PI (Chelsea Kahn): it does not appear in “open tasks,” but it does appear in “closed tasks”
3. In troubleshooting, we changed the reporting end date to 5/31/16 and then changed it back to 9/30/15, the change to 5/31/16 did not make it appear under “open tasks,” and even though we changed it back, it still has 5/31/16 as the reporting end date in the heading information on the new report
4. When PI (Chelsea Kahn) went in and started the report: “due date” at the top says “no due date set” even though it had a deadline of 3/31/16 in the reporting call.
5. Created the project E/H-2014-Bogeberg and made Chelsea Kahn the original PI, then switched PI to Kate Litle, then switched back to Chelsea Kahn: However, this project/report assignment is not showing up for her… (Marcus / Kate at WASG)

**Comment by ecsion** [comment]
fixed. Please verify and let us know if you still experience this issue.
