### ISSUE TITLE
 Add ‘Instructions’ text to Standard Modules in Report Call

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Bug-Tracker#96]
Please add ‘Instructions’ text at the top of each of the Standard Module forms, as follows:

Students Supported
These are students supported by Sea Grant through financial or other means. Please include students supported by Sea Grant, federal, match, and leveraged funds. New students are those not previously reported by you; continuing students are those previously reported and still supported by
your project.

Impacts and Accomplishments
Impact Statements describe significant economic, societal and/or environmental benefits resulting from your project work. Accomplishment Statements describe the key actions, activities or results of your project which may not yet have had a significant economic, societal and/or environmental benefit but lay the foundation for such a benefit in the future. Statements should be 250 words or less.

Publications
Enter citation and abstract for any previously unreported preprints, reprints, published articles, technical reports, books, book chapters, etc., that you have written in connection with this project; remember to upload a PDF of the publication. 

Narratives
For an Update Report, please submit a narrative report of five, double-spaced pages describing your project work during this reporting period. Describe methods with sufficient detail so that the validity of scientific findings or technological work can be evaluated, and replication would be possible. Include information on vendors, laboratory tests, field missions and any helpful discoveries of a practical or theoretical nature. The report should be in PDF format and may include images, charts, tables, and equations.
Completion Reporting requires a final narrative covering the entire life of a project. We ask for twenty, double-spaced pages that document the conduct of a project with sufficient detail so that the validity of its findings can be evaluated, and replication of the study would be possible. The narrative should detail project methodology and data analysis. The following are acceptable as substitutes for an original report, as long as they fully cover the project work in the manner described above: one or more journal articles, in draft or published form; one or more graduate student dissertations or theses. 

Partners
List any organizations, agencies, community groups, municipalities, governments, businesses laboratories, or other partners with whom you worked on this project.

**Comment by ecsion** [comment]
done.
